FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o consumer .

FROM scratch
COPY --from=builder /app/consumer /consumer
ENTRYPOINT ["/consumer"]
