# Producer: 1 pod simulating the AV fleet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: geoscale-producer:latest
          imagePullPolicy: Never # use local image loaded via minikube
          env:
            - name: KAFKA_BROKER
              value: "host.minikube.internal:9092"
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
